### ISSUE TITLE
The image used to synthetic anomaly

### ISSUE THREAD

**Issue by hxx-who** [tzjtatata/Myriad#6]
Hi, great work!
I was wondering, Do the image used to synthetic anomaly and the original image come from the same object category? or the image used to synthetic anomaly is just ramdomly selected in the whole dataset?

**Comment by tzjtatata** [comment]
Thank you. We synthesis with images from the whole datasets.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Thu, Jan 18, 2024 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [tzjtatata/Myriad] The image used to synthetic anomaly (Issue #6)




 
Hi, great work!
 I was wondering, Do the image used to synthetic anomaly and the original image come from the same object category? or the image used to synthetic anomaly is just ramdomly selected in the whole dataset?
